# Generated by Django 5.1.4 on 2026-01-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HELD', 'Held'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seats.seat')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='seats.show'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seats.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seats.show')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('show', 'seat_number')},
        ),
    ]
