# Generated by Django 5.1.4 on 2026-01-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_remove_seathold_seat_alter_seat_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='held_untill',
            new_name='held_until',
        ),
    ]
